/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 24.11
 * Usage: Interface to C
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HC_HALCON_DAHENG
#define HC_HALCON_DAHENG

#ifndef __APPLE__
#  include "HalconC.h"
#else
#  ifndef HC_LARGE_IMAGES
#    include <HALCONC/HalconC.h>
#  else
#    include <HALCONCxl/HalconC.h>
#  endif
#endif

#if defined(__cplusplus)
extern "C" {
#endif

HUserExport Herror T_DHGXGetIntValue(const Htuple CameraHandle, const Htuple strFeatureID, Htuple *nValue);
HUserExport Herror DHGXGetIntValue(Hlong CameraHandle, const char *strFeatureID, Hlong *nValue);
HUserExport Herror T_DHGXGetBoolValue(const Htuple CameraHandle, const Htuple strFeatureID, Htuple *bValue);
HUserExport Herror DHGXGetBoolValue(Hlong CameraHandle, const char *strFeatureID, Hlong *bValue);
HUserExport Herror T_DHGXGetEnumValue(const Htuple CameraHandle, const Htuple strFeatureID, Htuple *nValue);
HUserExport Herror DHGXGetEnumValue(Hlong CameraHandle, const char *strFeatureID, Hlong *nValue);
HUserExport Herror T_DHGXGetFloatValue(const Htuple CameraHandle, const Htuple strFeatureID, Htuple *dValue);
HUserExport Herror DHGXGetFloatValue(Hlong CameraHandle, const char *strFeatureID, double *dValue);
HUserExport Herror T_DHGXSetIntValue(const Htuple CameraHandle, const Htuple strFeatureID, const Htuple nValue);
HUserExport Herror DHGXSetIntValue(Hlong CameraHandle, const char *strFeatureID, Hlong nValue);
HUserExport Herror T_DHGXSetBoolValue(const Htuple CameraHandle, const Htuple strFeatureID, const Htuple bValue);
HUserExport Herror DHGXSetBoolValue(Hlong CameraHandle, const char *strFeatureID, Hlong bValue);
HUserExport Herror T_DHGXSetEnumValue(const Htuple CameraHandle, const Htuple strFeatureID, const Htuple nValue);
HUserExport Herror DHGXSetEnumValue(Hlong CameraHandle, const char *strFeatureID, Hlong nValue);
HUserExport Herror T_DHGXSetFloatValue(const Htuple CameraHandle, const Htuple strFeatureID, const Htuple dValue);
HUserExport Herror DHGXSetFloatValue(Hlong CameraHandle, const char *strFeatureID, double dValue);
HUserExport Herror T_DHGXSetCommandValue(const Htuple CameraHandle, const Htuple strKey);
HUserExport Herror DHGXSetCommandValue(Hlong CameraHandle, const char *strKey);
HUserExport Herror T_DHGXOPenCameraByID(const Htuple Name, const Htuple TimeSharingFlicker, const Htuple CameraType, const Htuple QueueHandle, Htuple *CameraHandle);
HUserExport Herror DHGXOPenCameraByID(const char *Name, Hlong TimeSharingFlicker, Hlong CameraType, Hlong QueueHandle, Hlong *CameraHandle);
HUserExport Herror T_DHGXCloseLib(void);
HUserExport Herror DHGXCloseLib(void);
HUserExport Herror T_DHGXGetLastError(Htuple *msg, Htuple *errcode);
HUserExport Herror DHGXGetLastError(char *msg, Hlong *errcode);
HUserExport Herror T_DHGXInitLib(void);
HUserExport Herror DHGXInitLib(void);
HUserExport Herror T_DHGXGetLogType(Htuple *ui32LogType);
HUserExport Herror T_DHGXSetLogType(const Htuple ui32LogType);
HUserExport Herror DHGXSetLogType(Hlong ui32LogType);


#if defined(__cplusplus)
}
#endif

#endif
